// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzkrdjtbdtyhiavhxker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3JkanRiZHR5aGlhdmh4a2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjAyNjUsImV4cCI6MjA1OTQzNjI2NX0.eJltmy6OHNh2r8iN_1I3n_Sl8PLHI5V5KNHCUBLgNlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);